name: Deploy Static Web App

on:
  push:
    branches:
      - main  # Deploy on push to the main branch
  pull_request:
    branches:
      - main  # Deploy on pull requests to the main branch

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/"            # Location of your app source code
          api_location: ""             # Leave empty if you don't have an API
          output_location: "build"     # Location of the build output